name: Generate Pac-Man

on:
  # Run every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman
    steps:
      - uses: actions/checkout@v3
      - uses: kikobeats/github-action-pacman@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The following line commits the generated SVG to the root of your master branch
          svg_out_path: github-contribution-grid-pacman.svg
